volumes:
  db:

services:
  db:
    image: postgres:14.8
    container_name: klontong_db
    volumes:
      - ./infrastructure/postgres/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432

  app:
    container_name: klontong_api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    links:
      - db
